feat: Created function for add tickets
victor-carvalho1996/todo-list pull request #1
Opened 2022-07-18 21:54 UTC by victor-carvalho1996

## Motivation: 
- To implementation to task insert item in list It was created the pull request.

## Ilustration
![image](https://user-images.githubusercontent.com/76500875/179623435-a5f16eb6-952b-413a-bcba-7e52be8c29ae.png)

2022-07-19 18:33 UTC, vzsoares requested changes

2022-07-19 18:33 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +  textTask: string;
aqui o ideal seria criar um arquivo types.ts em /components/ e exportar essa interface de la, e tipagens futuras que serão utilizadas em diversos lugares também podem ser implementadas e exportadas do mesmo arquivo .

2022-07-19 18:33 UTC, vzsoares commented on src/App.tsx
> +  const [useListTask, setListTask] = useState<Task[]>([]);
esse nome nao esta de acordo com boas praticas de react. o prefixo `use` é utilizado para custom hooks [veja](https://pt-br.reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook).
```suggestion
  const [taskList, setTaskList] = useState<Task[]>([]);
```

2022-07-19 18:33 UTC, vzsoares commented on src/App.tsx
> +import TaskDashboard, { Task } from './components/TaskDashboard';
seria esse Task um objeto ? componente (pois tem o nome em maiúsculo) ou um tipo ??
 para facilitar aq como é um interface , colocar um `I` como prefixo pode ajuda bastante.
 
 > sugeri abaixo tambem a criaçao de um arquivo para centralizar os tipos da aplicaçao

2022-07-19 18:33 UTC, vzsoares commented on src/App.tsx
> +      id: useListTask.length,
em tasks futuras teremos que criar um id mais unico 
se quiser pode colocar apenas um comment de TODO 
` // TODO get unique ID `

2022-07-19 18:33 UTC, vzsoares commented on src/components/AddItemForm.tsx
> +  const [useTextTask, setTextTask] = useState<string>('');
necessário mudar o nome aqui como sugeri acima

2022-07-20 18:08 UTC, Guilherme-BS commented on src/App.tsx
> +      id: useListTask.length,
Tem uma biblioteca também chamada uuid, talvez seja uma boa opção

2022-07-20 21:32 UTC, victor-carvalho1996 commented on src/App.tsx
> +      id: useListTask.length,
Acabei utilizando a biblioteca uuid mesmo para fazer o id único para as tasks.

2022-07-20 21:33 UTC, victor-carvalho1996 commented on src/App.tsx
> +import TaskDashboard, { Task } from './components/TaskDashboard';
Crie um arquivo igual foi sugerido para centralizar as interfaces e os tipos.

2022-07-20 23:12 UTC, frattezi commented
Fala man, pequenas correções de inglês para deixar o PR na pinta:

**Nome do PR**: feat: create add tickets function
**Motivation**:  This PR implements a new function that will add a new ticket to the items list.

**Dicas gerais pro resto do PR**

- Lembre-se de se marcar como Asignee no canto direito, informa que você é o responsável pela alteração.
- Também no canto direito, marque seu PR com a Tag de `Enhancement` uma vez que você fez uma melhoria.

Eu sempre uso o [Grammarly](https://www.grammarly.com/) também, ele da uma super força na hora de escrever textos em inglês!

2022-07-20 23:34 UTC, frattezi reviewed
Fala meu mano, massa ver a aplicação tomando forma, fiz algums comments e sugestões de melhoria, se tiver qualquer dúvida pode me procurar e fazemos uma call

2022-07-20 23:34 UTC, frattezi commented on src/App.tsx
> +  const [taskList, setListTask] = useState<ITaskList[]>([]);
O padrão aqui seria seguir o mesmo nome do estado:

```suggestion
  const [taskList, setTaskList] = useState<ITaskList[]>([]);
```

2022-07-20 23:34 UTC, frattezi commented on src/App.tsx
> +    const newList: any = { ...taskList };
Você criou uma variável chama **task**List e colocou como valor inicial dela uma lista vazia. Porém quando o primeiro item é adicionado, este estado passa a ser um objeto. Isto causa para quem está lendo o código estranheza sempre queremos manter nossos tipos coerentes com seus nomes e contexto.

2022-07-20 23:34 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +          {Object.keys(tasks).map((element: any) => {
Se relaciona a meu comentário anterior sobre o formato do dado de task, este dado deveria ser uma lista, sendo assim não seria necessário passar por `Object.Keys` o código seria apenas:
```suggestion
          {tasks.map((element: any) => {
```

Oque é bem mais limpo e direto, pois o tipo do dado agora faz sentido com seu uso na aplicação. O nome também poderia ser `taskList` mantendo o padrão entre componentes e indicando o tipo no nome

2022-07-20 23:34 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +          {Object.keys(tasks).map((element: any) => {
O nome `element` no callback também não faz sentido, poderia ser `task`!

2022-07-20 23:34 UTC, frattezi commented on src/App.tsx
> +
Fiz algumas alterações no code como um todo e simplifiquei a função `handleAddTask` (poderia se chamar `addTask`). Perceba, como você já tem a interface `Task`, para se ter uma lista de tasks basta escrever `Task[]`. Com isto, também deletei o tipo ITaskList, pois ele representava um objeto, e não precisamos mais dele.

```suggestion
function App() {
  const [taskList, setListTask] = useState<Task[]>([]);

  const handleAddTask = (text: string) => {
    const newTask: Task = {
      id: uuidv4(),
      textTask: text,
      taskComplete: false,
    };

    setListTask([...taskList, newTask]);
  };

```

2022-07-20 23:43 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +          {Object.keys(tasks).map((element: any) => {
Veja também que, fazendo `element: any` você destipou a Task, o typescript ia te falar com clareza que se trata de 1 item da lista de tasks, porem colocando como any você perde a clareza de tipos, nunca colocamos any como tipos, sempre queremos manter os tipos corretos

2022-07-20 23:50 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +
Deveria ser:

```suggestion
interface TaskList {
  tasks: Task[];
}
```

O tipo ItaskList[] que você criou é uma lista de objetose e nesse objeto existe uma chave uuid com um objeto task

No final o objeto que você estava trabalhando ficava neste formato:
```javascript
[
  {
    12931923123: {
      id: '12931923123',
      textTask: 'test',
      taskComplete: false,
    },
  },
  {
    123123: {
      id: '123123',
      textTask: 'test',
      taskComplete: false,
    },
  },
];
```
Perceba que o ID é redundante e temos uma nova camada de objeto completamente desnecessária
O dado final, após minhas indicações seria:

```javascript
[
  {
    id: '12931923123',
    textTask: 'test',
    taskComplete: false,
  },
  {
    id: '12931231231923123',
    textTask: 'test',
    taskComplete: false,
  },
];
```

Veja como faz mais sentido e simplifica o acesso as tasks (veja meus outros comments sobre o tema)

2022-07-25 18:25 UTC, frattezi reviewed
Cara o PR teve uma evolução muiito boa! Os tipos estão ótimos também, todos corretos! Deixei apenas mais alguns detalhes de melhoria antes de irmos para o merge!

2022-07-25 18:25 UTC, frattezi commented on src/components/AddItemForm.tsx
>    const domInputId = 'new-todo-input';
[Sugestão]
Para simplificar o uso e reduzir uma linha o code poderia ficar assim:

```suggestion
function AddItemForm({ handleAdd }: IProps) {
  const domInputId = 'new-todo-input';
  // Agora é possível utilizar o nome handleAdd dentro da função normalmente!
```

2022-07-25 18:25 UTC, frattezi commented on src/components/AddItemForm.tsx
> +  const [taskText, setTextTask] = useState<string>('');
lembre-se que o padrão é o mesmo nome do estado com "set" a frente, aqui seria:
```suggestion
  const [taskText, setTaskText] = useState<string>('');
```

2022-07-25 18:25 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +function TaskDashboard(props: TaskList) {
Mesma coisa aqui, pode desempacotar diretamente nos paramêtros da função e evitar a próxima linha

2022-07-25 23:25 UTC, victor-carvalho1996 commented on src/components/AddItemForm.tsx
>    const domInputId = 'new-todo-input';
Ah certo, mas tenho uma dúvida em relação de boas práticas que é a seguinte: caso exista vários parametros nesse componentes, posso fazer direto na function ou é melhor criar um const e desestruturar a props igual fiz inicialmente?

2022-07-26 02:04 UTC, vzsoares approved these changes
ta ficando show em

2022-07-26 02:04 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +          {taskList.map((task: Task) => {
acho q aq o typescript infere o tipo sozinho, ja que o taskList esta tipado na linha 5

2022-07-26 02:04 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +interface TaskList {
```suggestion
interface TaskDashboardProps{
```
> ou ate
> ```suggestion
> interface Props{
> ```
futuramente provavelmente terao mais props e entao esse nome atual perdera o sentido

2022-07-26 17:35 UTC, frattezi commented on src/components/AddItemForm.tsx
>    const domInputId = 'new-todo-input';
Acho que de qualquer forma o aberto vai valer mais a pena, a interface e o autocomplete já vão demarcar bem a interface do componente.

Mas a sua escrita ainda é válida, mas acho que vai ser em situações mais como:
Imagine uma função que recebe como parametros:
- um objeto de configurações
- uma string a ser processada
- um booleano definindo um modificador

Aqui é interessante tratar este objeto de configurações e consumílo como você fez. Uma vez que, neste contexto, existe uma separação lógica clara entre cada paramêtro da função e configurações foi simplificado para um objeto único pois define um contexto para aquele dado.

2022-07-26 17:36 UTC, frattezi approved these changes
Vale resolver os comments do zenha, o PR está muito bom! 🚀

2022-07-26 22:18 UTC, victor-carvalho1996 commented on src/components/AddItemForm.tsx
>    const domInputId = 'new-todo-input';
Ah certo, deu para entender. Valeu pela explicação.

2022-07-26 22:27 UTC, victor-carvalho1996 commented on src/components/TaskDashboard.tsx
> +interface TaskList {
Valeu pela dica.

2022-07-26 22:29 UTC, merged