feat: added functionality to edit task.
victor-carvalho1996/todo-list pull request #5
Opened 2022-07-27 00:57 UTC by victor-carvalho1996

## Motivation:
- To edit one task it was created the pull request.

## Simulation
- To simulate editing the task, it is necessary to double click on the task label, from which the text will be available in the input. See gif below.

## Ilustration
![CPT2207201943-680x652](https://user-images.githubusercontent.com/76500875/180096879-c424f28d-83cb-427b-a07c-9512a0e0161a.gif)

2022-07-27 15:27 UTC, vzsoares requested changes
da pra dar uma simplificada boa aqui , se tiver duvida pode chamar!!

2022-07-27 15:27 UTC, vzsoares commented on src/App.tsx
> +  const [idEdit, setIdEdit] = useState<string>('');
aqui voce pode usar apenas a string pois ela possui a propriedade `true/false` implícita. [veja](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)

2022-07-27 15:27 UTC, vzsoares commented on src/App.tsx
> +  };
aqui voce pode só setar o estado do id e dps na funçao de editar voce usa ele para filtrar a lista e editar somente o que tiver o id que esta no estado 

```suggestion
  const startEditing = (id: string) => {
     setEditingID(id)
     setTaskText(taskList.filter( (task) => id  === task.id).text)
  };
```

2022-07-27 15:27 UTC, vzsoares commented on src/App.tsx
> +    }
```suggestion
  const editTask = () => {
setTaskList(taskList.map((task)=>{
if(task.id === editingId) return {...task,text:taskText}
else return task}))

    resetStates();
  };
```

2022-07-27 22:26 UTC, frattezi reviewed
Meu comment aponta uma mudança na estrutura de estado da aplicação, acredito que vai acarretar em oturas mudanças na função.

Veja se concorda comigo, qualquer dúvida é só me mandar mensagem!

2022-07-27 22:26 UTC, frattezi commented on src/App.tsx
> +  const [taskText, setTaskText] = useState<string>('');
Fala Vitor! Man penso que aqui poderíamos simplificar e evitar criar um state apenas para o texto e um isEdit e idEdit.

Acredito que você poderia trocar toda essa estrutura e manter apenas:
```javascript
  const [taskList, setTaskList] = useState<Task[]>([]);
  const [selectedTask, setSelectedTask] = useState<Task | undefined>();
```
Tendo essa estrutura de memória, você poderá começar a simplificar suas funções. Quando a pessoa selecionar uma task para edição, ao invés de setar texto, id e isEdit você poderia apenas setar a `selectedTask` com os dados de `taskList[id]`. Assim, ao invés de checar o booleano isEdit, você precisa apenas verificar se a `selectedTask` é undefined ou não, para usar seu  texto basta acessar `selectedTask.text` etc etc etc.


Acredito que isto simplificaria seu código como um todo; Se tiver dúvidas pode me procurar. Valeu!

2022-07-28 00:49 UTC, victor-carvalho1996 commented on src/App.tsx
> +  const [idEdit, setIdEdit] = useState<string>('');
Valeu pela dica Zenha, mas nesse caso segui a ideia do Fratezzi para unificar o idEdit e isEdit em apenas um state.

2022-07-28 00:50 UTC, victor-carvalho1996 commented on src/App.tsx
> +    }
Valeu, usei a idéia da única função para editar task como você indicou acima.

2022-07-28 00:55 UTC, victor-carvalho1996 commented on src/App.tsx
> +  const [taskText, setTaskText] = useState<string>('');
Gostei da idéia sim e implementei ela. Mas o state de taskText eu precisei manter ele, pois uso o mesmo para ser o state de change do input de texto. Acabei nessa branch deslocando ele do arquivo AddItemForm.tsx para App.tsx, pois ele ficando nesse local foi melhor para mim manipular o edit da task , mas também posso estar errado nesse pensamento. Sigo aberto a sugestões...

2022-07-28 14:56 UTC, vzsoares approved these changes
show show . quase na hora do context em !!!!!!

2022-07-28 14:56 UTC, vzsoares commented on src/App.tsx
> +    setTaskText('');
resetStates?

2022-07-28 14:56 UTC, vzsoares commented on src/App.tsx
> +  const clickEdit = (id: string) => {
```suggestion
  const startEditing = (id: string) => {
```

2022-07-28 14:56 UTC, vzsoares commented on src/App.tsx
> +        handleEdit={editTask}
pode usar os nomes iguais aqui , bom q evita confusao
ex 
...
handleEdit={handleEdit}
...

2022-07-28 21:31 UTC, frattezi commented on src/App.tsx
> +    const taskToEdit: Task[] = taskList.filter((task: Task) => {
Acho que aqui o melhor seria utilizar a função [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

2022-07-28 21:31 UTC, frattezi commented on src/App.tsx
> +    const taskToEdit: Task[] = taskList.filter((task: Task) => {
Assim você não precisa ficar acessando [0]

2022-07-28 21:31 UTC, frattezi commented on src/App.tsx
> +    setTaskText(taskToEdit[0].textTask);
Este espaço entre as funções não é necessários
Geralmente você quer separar em blocos mesmo como você já faz, mas acho que isto aqui poderia estar junto, em todas as functions
```suggestion
    setSelectedTask(taskToEdit[0]);
    setTaskText(taskToEdit[0].textTask);
```

2022-07-31 14:56 UTC, frattezi approved these changes
Muito bom mano, obrigado por considerar os comentários! 🚀

2022-07-31 17:08 UTC, merged