feat: create function to remove task.
victor-carvalho1996/todo-list pull request #7
Opened 2022-07-31 18:11 UTC by victor-carvalho1996

## Motivation:
- To remove one task it was created the pull request.
## Simulation
- To simulate the remove task, it is necessary to click in "Delete" button, from which the task will be removed from the list of tasks. See gif below.
## Illustration:
![CPT2207311443-739x698](https://user-images.githubusercontent.com/76500875/182039635-5882312f-b3a0-4620-9cae-6c4a4477c666.gif)

2022-07-31 19:53 UTC, vzsoares requested changes
em relaçao a logica ta show! só q acho q vc confudiu com relaçao ao layout
a ideia era manter o design como o original msm 
> ex 
![image](https://user-images.githubusercontent.com/86134825/182042794-82019f84-1990-4faa-ba06-676c55e5e48a.png)

no caso o botao save/edit faz parte de cada task individual

2022-07-31 23:01 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +          <ul
o <ul  representa uma lista de items e o <li representa um item entao o correto aq é o ul estar fora do map e o map em si retornar os <li ou items da lista. [veja](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul)

2022-07-31 23:51 UTC, victor-carvalho1996 commented on src/components/TaskDashboard.tsx
> +          <ul
Ah certo, valeu pelo retorno. Correção realizada.

2022-07-31 23:57 UTC, vzsoares approved these changes
bruto

2022-08-01 18:14 UTC, frattezi approved these changes
Por favor apenas configra meu último comentário talvez o zenha saiba melhor, De qualquer forma, se formos seguir oque falei, acho que pode ser uma tarefa separada.

O código ficou muito bom e os PR's muito bem detalhados, parabéns!

2022-08-01 18:14 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +            <li className="todo stack-small">
Man está ficando muito bom, tenho apenas um pedido para fazer, se você achar legal pode até dividir e fazer em outro PR. O comentário que o zenha fez foi muito bom pois era algo que estava me causando estranheza a forma de edição pois nem me lembrava como os meninos haviam feito.

Agora o fluxo faz muito mais sentido, queria apenas te pedir para fazer, nesta parte do código:

 - Remover oque está dentro deste return e criar este componente como um novo componente.
 - Será que conseguimos fazer a ediçaõ do step ficar no próprio passo? E não na barra principal? Me parece fazer mais sentido

@vzsoares quando vocês fizeram como era esta parte de edição? Se vocês tiverem feito dessa mesma forma que o Victor podemos ignorar meu comment.

2022-08-01 19:27 UTC, vzsoares commented on src/components/TaskDashboard.tsx
> +            <li className="todo stack-small">
particulamente me lembro de ter feito uma funçao startEditinge e uma editTask , e a task foi separada para outro componente mesmo.

2022-08-01 22:24 UTC, victor-carvalho1996 commented on src/components/TaskDashboard.tsx
> +            <li className="todo stack-small">
Ah certo, vou dar o merge desse PR já que ele está aprovado, aí no próximo já faço essa correções.

2022-08-01 22:24 UTC, merged

2022-08-01 22:53 UTC, frattezi commented on src/components/TaskDashboard.tsx
> +            <li className="todo stack-small">
Perfeito mano, valeu!

2022-08-01 23:06 UTC, victor-carvalho1996 commented on src/components/TaskDashboard.tsx
> +            <li className="todo stack-small">
Só uma duvida @frattezi, quando voce falou **"Será que conseguimos fazer a ediçaõ do step ficar no próprio passo? E não na barra principal? Me parece fazer mais sentido"**,  eu fiquei sem enteder, teria como me explicar melhor sobre?